SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[aaa_floodriskorder] (
	[OrderID] [int] IDENTITY(1,1) NOT NULL,
    [aai_floodriskorderid] uniqueidentifier,
    [aai_account] uniqueidentifier,
    [aai_accountname] nvarchar(160),
    [aai_accountyominame] nvarchar(160),
    [aai_additionalinformation] nvarchar(max),
    [aai_address1_matched] nvarchar(200),
    [aai_address1_orig] nvarchar(200),
    [aai_address2_matched] nvarchar(100),
    [aai_address2_orig] nvarchar(100),
    [aai_addressparcelnumber] nvarchar(106),
    [aai_borrower] nvarchar(200),
    [aai_borrower2] nvarchar(100),
    [aai_branch] uniqueidentifier,
    [aai_branchname] nvarchar(160),
    [aai_branchyominame] nvarchar(160),
    [aai_citymatched] nvarchar(100),
    [aai_cityorig] nvarchar(100),
    [aai_compliancenotes] nvarchar(max),
    [aai_crbadate] datetime,
    [aai_distancebuffer] nvarchar(100),
    [aai_emailcertcc] nvarchar(100),
    [aai_emailcertto] nvarchar(100),
    [aai_enteredcountry] nvarchar(20),
    [aai_floodcasenumber] nvarchar(100),
    [aai_floodcommunity] nvarchar(200),
    [aai_floodcommunitynumber] nvarchar(100),
    [aai_floodcounty] nvarchar(100),
    [aai_flooddeterminationdate] datetime,
    [aai_flooddeterminationstatus] int,
    [aai_flooddeterminationstatusname] nvarchar(255),
    [aai_floodinfozone] nvarchar(10),
    [aai_floodmapdate] date,
    [aai_floodmapdate2] date,
    [aai_floodmapnumber] nvarchar(100),
    [aai_floodmapnumber2] nvarchar(100),
    [aai_floodnfipstatus] int,
    [aai_floodnfipstatusname] nvarchar(255),
    [aai_floodordercontactid] uniqueidentifier,
    [aai_floodordercontactidname] nvarchar(160),
    [aai_floodordercontactidyominame] nvarchar(450),
    [aai_fullenteredaddress] nvarchar(200),
    [aai_fullenteredaddressformatted] nvarchar(4000),
    [aai_fullmatchedlegaladdress] nvarchar(200),
    [aai_fzdistance] nvarchar(100),
    [aai_hasnomap] bit,
    [aai_hasnomapname] nvarchar(255),
    [aai_hmda] nvarchar(100),
    [aai_isurgent] bit,
    [aai_isurgentname] nvarchar(255),
    [aai_loannumber] nvarchar(100),
    [aai_loanstatus] int,
    [aai_loanstatusname] nvarchar(255),
    [aai_loantype] int,
    [aai_loantypename] nvarchar(255),
    [aai_locationlat] float,
    [aai_locationlong] float,
    [aai_lomadate] datetime,
    [aai_matchedcountry] nvarchar(50),
    [aai_name] nvarchar(100),
    [aai_orderdate] datetime,
    [aai_orderedby] uniqueidentifier,
    [aai_orderedbyname] nvarchar(160),
    [aai_orderedbyyominame] nvarchar(450),
    [aai_ordernumber] nvarchar(100),
    [aai_ordertype] int,
    [aai_ordertypename] nvarchar(255),
    [aai_processor] uniqueidentifier,
    [aai_processorname] nvarchar(160),
    [aai_processoryominame] nvarchar(160),
    [aai_statematched] nvarchar(4),
    [aai_stateorig] nvarchar(4),
    [aai_zipmatched] nvarchar(10),
    [aai_ziporig] nvarchar(10),
    [createdby] uniqueidentifier,
    [createdbyname] nvarchar(200),
    [createdon] datetime,
    [importsequencenumber] int,
    [modifiedby] uniqueidentifier,
    [modifiedbyname] nvarchar(200),
    [modifiedon] datetime,
    [ownerid] uniqueidentifier,
    [owninguser] uniqueidentifier)

GO